### ISSUE TITLE
Incorrect rendering around the eyes

### ISSUE THREAD

**Issue by liuzhihui2046** [zhuhao-nju/facescape#31]
Thank you for your excellent work. I encountered some problems in rendering face. The textures
Around the eyes is not smooth, I guess there is something wrong with the triangle number in this part? Has anyone else encountered similar problems? Can you give me some advise?
![facescape_render](https://user-images.githubusercontent.com/11583071/92484407-388d1e80-f21c-11ea-82ae-8b15af3389f3.png)

**Comment by zhuhao-nju** [comment]
Hi, the texture map of the models with id 360 - 847 are mosaics around the eyes mannually, while the geometry of the mesh is correct.  This is because some of the paticipants do not want to make their portraits public, so we blur the texture to prevent them from being identified.  We have illustrated this in the "Data Description" in https://facescape.nju.edu.cn/Page_Data/.

**Comment by liuzhihui2046** [comment]
> Hi, the texture map of the models with id 360 - 847 are mosaics around the eyes mannually, while the geometry of the mesh is correct. This is because some of the paticipants do not want to make their portraits public, so we blur the texture to prevent them from being identified. We have illustrated this in the "Data Description" in https://facescape.nju.edu.cn/Page_Data/.

Thank you very much!!!
