### ISSUE TITLE
How to get the yaw,pitch,roll from the rotation matrix in multi view data?

### ISSUE THREAD

**Issue by xianzhongma** [zhuhao-nju/facescape#41]
Hi, I want to get the Euler angles from the params.json file in multi-view data. But I find that it is not consistent for different IDs. In details, the yaw,pitch,roll value  for front-view of some ID  is not the same as that of another ID. 
I want to use this information to find some specific-view images. Could you give me some suggestions about filtering the images? Thanks!

**Comment by zhuhao-nju** [comment]
Hi @xianzhongma , sorry for the late reply.  
The coordinates of multi-view data differs from each other, because they are generated by Structure-from-Motion with uncertain initialization.  To align all the multi-view meshes, you can transform them to the uniform TU-model coordinates (refer to https://github.com/zhuhao-nju/facescape/issues/39#issuecomment-735561112), then you can filter cameras according to the transformed yaw,pitch,roll value.

"match_num" means the number of valid feature matching, which is a value reported by Structure-from-Motion algorithm.  Generally, the higher "match_num" means this image is clear and with correct calibration.  If a "match_num" is low, it may caused by some of those problems: 1) the image is blury (unfocused); 2) the calibration is inaccurate; 3) the camera doesn't aim at the frontal face.  These problems are very rare, but to be prudential, the images with low "match_num" can be filtered out.

**Comment by xianzhongma** [comment]
Thanks for your detailed answer!
