### ISSUE TITLE
No such file: "./facescape_trainset_001_100/66/models_reg/3_mouth_stretch.jpg" 

### ISSUE THREAD

**Issue by goddice** [zhuhao-nju/facescape#47]
Hello, this specific file seems missing from the dataset. Could check it? Thanks!

**Comment by zhuhao-nju** [comment]
Hi @goddice ,
There are some files in our TU models that cannot be generated correctly due to technical problems, and the file you mentioned is one of them. Fortunately, there are few such exceptions.  
I would recommend skipping these missing file when doing batch processing, and you may filter them out using the label in the info_list, which is explained here:
https://github.com/zhuhao-nju/facescape/blob/master/doc/doc_tu_model.md#information-list
