### ISSUE TITLE
How to use the vertex_color PCA model? 

### ISSUE THREAD

**Issue by PxinLi** [zhuhao-nju/facescape#63]
Hi,

I find the 'color_bm_core' and 'color_bm_mean' in 'facescape_bm_v1.6_847_50_52_id_front'.  And I get the color by

vc_vec= (np.random.random(100) - 0.5) * 100
vert_colors = self.color_bm_mean + self.color_bm_core.dot(vc_vec)
vert_colors = vert_colors.reshape((-1, 3)) / 255

the 'color_bm_mean' and the 'self.color_bm_core.dot(vc_vec)' as follows:

color_bm_mean
[ 77.04486  91.19363 133.28926 ...  83.27036 101.74144 154.63872]
self.color_bm_core.dot(vc_vec)
[-1.97144967 -1.29185722 -1.32739323 ...  1.08921361  1.73029627
  1.26778769]

I find that the 'vc_vec' had little effect on the resulting vertex color.  Is there eigenvalue variances of the color pca model?

**Comment by ForrestPi** [comment]
yeah same confusion，could you provide UV texture instead of  vertex color？   @zhuhao-nju

**Comment by zhuhao-nju** [comment]
We didn't compute PCA model for UV textures since they're too huge for traditional PCA computation, and maybe a non-linear model like neural network is more suitable. I believe an efficient parametric model for texture is still an open problem, and all the UV texture files have been released in our dataset to try different solutions.

**Comment by lyx323** [comment]
已收到
