### ISSUE TITLE
Hope you will release this under a license for commercial use MIT?

### ISSUE THREAD

**Issue by delebash** [zhuhao-nju/facescape#8]
There are datasets available for use but most of them are under academic license for non commercial use.  It would be wonderful if the academic community would release code and datasets for commercial use as well.  You could require any updates to the code to be sent back to the github repo with the license also containing citations.  In this case you can get valuable data from real world use in addition to giving back to the non-academic community. One of the reasons I ask is that  we non-academic programmers help find bug fixes and provide code improvements to many academic projects that can only be used for research.

Thanks for your consideration

Daniel

I really really look forward to you all trying a different approach then most other institutions.

**Comment by zhuhao-nju** [comment]
Hi Daniel, @delebash 
Sincerely thank you for the advice!  
We plan to publish the code and parametric models under MIT license, but we have to insist on non-commercial license for 3D models. The reason is that the face data involves the privacy of participants, and we have to ensure that participants' portraits are not abused.  Hope you could understand our efforts to protect the rights of participants.

Hao

**Comment by delebash** [comment]
I understand.  Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
