### ISSUE TITLE
Access to the website

### ISSUE THREAD

**Issue by yjhong89** [zhuhao-nju/facescape#81]
Dear authors, 

I am YJHong and thanks for your great work!

While I am accessing website to get a license, (https://facescape.nju.edu.cn/) 
I got this message
![image](https://user-images.githubusercontent.com/26890721/154186664-8cb66b25-b7f3-45ef-be8c-1e43d496ae9c.png)

Is it temporal shutdown ? 

Thank you.
Best regards, 
YJHong

**Comment by lyx323** [comment]
已收到

**Comment by zhuhao-nju** [comment]
Hi YJHong,

Thanks for your interest! The website is temporally shutdown due to the maintenance and will resume by 2022/2/21. During the maintenance, you may sign the agreement below and send it to facescape@outlook.com, then I will reply with the license key and google share link.

The google share link is used for downloading without login within two weeks, and the license key is used for login and downloading after the website resumes.

License agreement:
https://github.com/zhuhao-nju/facescape/blob/master/doc/License_Agreement.pdf

**Comment by yjhong89** [comment]
@zhuhao-nju 
Thank you for reply.
I send the license agreement with my signature

Thank you (close this issue)
